version: "3.1"
services:
  mysql:
    image: mysql:8.4-oraclelinux9
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=12345678"
    volumes:
      - "mysqldata:/var/lib/mysql"
  webserver:
    build: .webserver
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html/"
      - "./.webserver/000-default.conf:/etc/apache2/sites-enabled/000-default.conf"
volumes:
  mysqldata: null